service: mobility # NOTE: update this with your service name

plugins:
  - serverless-wsgi
  - serverless-python-requirements

provider:
  name: aws
  runtime: python3.6
  stage: v1
  region: eu-central-1

custom:
  wsgi:
    app: api/app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
