service: mobility # NOTE: update this with your service name

plugins:
  - serverless-wsgi
  - serverless-python-requirements

provider:
  name: aws
  runtime: python3.6
  stage: v1
  region: eu-central-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "arn:aws:dynamodb:eu-central-1:712196630605:table/Provider-4adrckwckzhjzfl47kknke3uvm-dev"
        - "arn:aws:dynamodb:eu-central-1:712196630605:table/Trip-4adrckwckzhjzfl47kknke3uvm-dev"
        - "arn:aws:dynamodb:eu-central-1:712196630605:table/User-4adrckwckzhjzfl47kknke3uvm-dev"
        - "arn:aws:dynamodb:eu-central-1:712196630605:table/Vehicle-4adrckwckzhjzfl47kknke3uvm-dev"
  environment:
    VEHICLE_TABLE: ${self:custom.vehicleTable}
    PROVIDER_TABLE: ${self:custom.providerTable}
    USER_TABLE: ${self:custom.userTable}
    TRIP_TABLE: ${self:custom.tripTable}

custom:
  vehicleTable: 'Vehicle-4adrckwckzhjzfl47kknke3uvm-dev'
  providerTable: 'Provider-4adrckwckzhjzfl47kknke3uvm-dev'
  tripTable: 'Trip-4adrckwckzhjzfl47kknke3uvm-dev'
  userTable: 'User-4adrckwckzhjzfl47kknke3uvm-dev'
  wsgi:
    app: api/app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux
    
functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
