service: mobility # NOTE: update this with your service name

plugins:
  - serverless-wsgi
  - serverless-python-requirements

provider:
  name: aws
  runtime: python3.6
  stage: v1
  region: eu-central-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["VehicleDBTable", "Arn" ] }
  environment:
    VEHICLE_TABLE: ${self:custom.vehicleTable}

custom:
  vehicleTable: 'Vehicle-4adrckwckzhjzfl47kknke3uvm-dev'
  wsgi:
    app: api/app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux
    
functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

resources:
  Resources:
    VehicleDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: ${self:custom.vehicleTable}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        

